version: 2.1

workflows:
  my-workflow:
    jobs:
      - test:
          context:
            - docker-env

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.3
        auth:
          username: yukoono
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "bundle install"
          command: "bundle install"
      - run:
          name: "database migrate"
          command: "bundle exec rails db:migrate"
      - run:
          name: "rails test"
          command: "bundle exec rails test"
